# Generated by Django 3.2.9 on 2021-11-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20211126_0916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='QR',
        ),
    ]
